module.exports = {
  apps: [
    {
      name: 'api-vallex-affiliates',
      cwd: '/root/painel-mt-affiliates/backend-vexxa',
      script: 'dist/src/main.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      kill_timeout: 8000,
      env: {
        NODE_ENV: 'production',
        PORT: '3001',
        REDIS_DB: '5',
      },
    },
    {
      name: 'affiliates-vallex',
      cwd: '/root/painel-mt-affiliates/frontend',
      script: '.output/server/index.mjs',
      instances: Number(process.env.WEB_CONCURRENCY || 2),
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      kill_timeout: 8000,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: '3000',
        NITRO_HOST: '0.0.0.0',
        NITRO_PORT: '3000',
        NUXT_PUBLIC_API_URL: '/api',
        NUXT_INTERNAL_API_URL: 'http://127.0.0.1:3001',
        NUXT_API_PROXY_TIMEOUT_MS: '15000',
        NUXT_PUBLIC_SOCKET_URL: 'https://api.mtafiliates.com.br',
      },
    },
    {
      name: 'admin-vallex',
      cwd: '/root/painel-mt-affiliates/admin',
      script: '.output/server/index.mjs',
      instances: Number(process.env.WEB_CONCURRENCY || 2),
      exec_mode: 'cluster',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      kill_timeout: 8000,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: '4174',
        NITRO_HOST: '0.0.0.0',
        NITRO_PORT: '4174',
        NUXT_PUBLIC_API_URL: '/api',
        NUXT_INTERNAL_API_URL: 'http://127.0.0.1:3001',
        NUXT_API_PROXY_TIMEOUT_MS: '15000',
        NUXT_PUBLIC_SOCKET_URL: 'https://api.mtafiliates.com.br',
      },
    },
    {
      name: 'telegram-vallex-bot',
      cwd: '/root/painel-mt-affiliates/telegram',
      script: 'dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      kill_timeout: 8000,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
      },
    },
  ],
}
