/**
 * Fresh MongoDB → PostgreSQL migration.
 *
 * SEEDS (upsert, always): betting_houses, deals, settings, provider_accounts, provider_account_houses
 * CLEARS & RE-MIGRATES: everything else from MongoDB (mjmcompany)
 * financial_ledger: cleared but NOT re-migrated (no Mongo source — generated by the app on-demand)
 *
 * Run: npx tsx prisma/migrate-fresh.ts
 */

import { MongoClient, ObjectId } from 'mongodb';
import {
  PrismaClient,
  UserRole,
  UserStatus,
  WithdrawalStatus,
  LinkRequestStatus,
  SyncMode,
} from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { randomUUID } from 'crypto';

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is required`);
  return value;
}

const MONGO_URI = process.env['MONGO_URI'] ?? '';
if (!MONGO_URI) throw new Error('MONGO_URI is required');
const DATABASE_URL =
  process.env['DATABASE_URL'] ??
  'postgresql://vexxa_user:vexxa_password@localhost:5433/vexxa_db?schema=public';
const adapter = new PrismaPg({ connectionString: DATABASE_URL });
const prisma = new PrismaClient({ adapter });

// ─── ObjectId → UUID mapping ────────────────────────────────────
const idMap = new Map<string, string>();

function mapId(mongoId: string | ObjectId | null | undefined): string | null {
  if (!mongoId) return null;
  const key = mongoId.toString();
  if (!idMap.has(key)) idMap.set(key, randomUUID());
  return idMap.get(key)!;
}

function ensureId(mongoId: string | ObjectId): string {
  return mapId(mongoId)!;
}

function toDate(v: unknown): Date {
  if (v instanceof Date) return v;
  if (typeof v === 'string' || typeof v === 'number') return new Date(v);
  return new Date();
}

function toDecimal(v: unknown): number {
  if (typeof v === 'number') return v;
  if (typeof v === 'string') return parseFloat(v) || 0;
  return 0;
}

// ─── House slug normalization (Mongo aliases → PG canonical slugs) ───
const HOUSE_NORM: Record<string, string> = {
  mjm: 'mgm',
  'bet mgm': 'mgm',
  MJM: 'mgm',
  'BET MGM': 'mgm',
  Superbet: 'superbet',
  Esportivabet: 'esportivabet',
  EsportivaBET: 'esportivabet',
};

function normalizeHouse(raw: string): string {
  const trimmed = raw.trim();
  return HOUSE_NORM[trimmed] ?? trimmed.toLowerCase();
}

// ─── Deal ObjectId → PG UUID mapping (built from slug match) ────
const dealIdMap = new Map<string, string>();

async function buildDealMap(mongo: MongoClient) {
  console.log(
    '\n🔗 Building deal ID map (Mongo ObjectId → PG UUID via slug)...',
  );
  const mongoDeals = await mongo
    .db()
    .collection('deals')
    .find({})
    .project({ _id: 1, bettingHouseSlug: 1 })
    .toArray();
  const pgDeals = await prisma.deal.findMany({
    select: { id: true, bettingHouseSlug: true },
  });
  const pgBySlug = new Map(pgDeals.map((d) => [d.bettingHouseSlug, d.id]));

  for (const md of mongoDeals) {
    const slug = normalizeHouse(md.bettingHouseSlug ?? '');
    const pgId = pgBySlug.get(slug);
    if (pgId) {
      dealIdMap.set(md._id.toString(), pgId);
      console.log(`   ${md._id} (${slug}) → ${pgId}`);
    }
  }
  console.log(`   ✅ ${dealIdMap.size} deals mapped`);
}

function mapDealId(
  mongoId: string | ObjectId | null | undefined,
): string | null {
  if (!mongoId) return null;
  return dealIdMap.get(mongoId.toString()) ?? null;
}

// ─── Step 0: Seed static/preserved tables ─────────────────────────────────
// These run via UPSERT — safe to call even if data already exists.

async function seedBettingHouses() {
  console.log('\n🏠 Seeding BettingHouses...');

  const houses = [
    {
      id: 'd19ece2d-28be-4839-b441-e1a5a4e9c7f9',
      name: 'BET MGM',
      slug: 'mgm',
      apiBaseURL: 'https://api-affiliates.mgaffiliates.site/api',
      apiBasePath: '/api/reports/v2/details',
      apiKey: '5c004b48-4213-4e1e-b028-01739154c10b',
      active: true,
      syncSchedule: '0 */2 * * *',
      syncMode: SyncMode.AUTO,
      logoUrl: '',
      withdrawalDay: null,
      withdrawalDayEnd: null,
    },
    {
      id: '55ecf539-c375-48b6-a524-ddf89f4c35ee',
      name: 'EsportivaBET',
      slug: 'esportivabet',
      apiBaseURL: 'https://api-affiliates.mgaffiliates.site/api',
      apiBasePath: '/api/reports/v2/details',
      apiKey: '02510c60-e702-479e-ada2-017e0b77f762',
      active: true,
      syncSchedule: '0 */2 * * *',
      syncMode: SyncMode.AUTO,
      logoUrl: 'https://mansaogreen.com/wp-content/uploads/2026/03/1740997404-superbet.png',
      withdrawalDay: null,
      withdrawalDayEnd: null,
    },
    {
      id: '79fc1dbb-fdfb-4f76-8e1b-2c6dfe51c5ba',
      name: 'Superbet',
      slug: 'superbet',
      apiBaseURL: 'https://api-affiliates.mgaffiliates.site/api',
      apiBasePath: '/api/reports/v2/details',
      apiKey: 'aad5fd62-ee9a-4d36-8f72-6f363ca59e13',
      active: true,
      syncSchedule: '0 */2 * * *',
      syncMode: SyncMode.AUTO,
      logoUrl: 'https://mansaogreen.com/wp-content/uploads/2026/03/1740997404-superbet.png',
      withdrawalDay: 20,
      withdrawalDayEnd: null,
    },
  ];

  for (const h of houses) {
    await prisma.bettingHouse.upsert({
      where: { slug: h.slug },
      update: {
        name: h.name,
        apiBaseURL: h.apiBaseURL,
        apiBasePath: h.apiBasePath,
        apiKey: h.apiKey,
        active: h.active,
        syncSchedule: h.syncSchedule,
        syncMode: h.syncMode,
        logoUrl: h.logoUrl,
        withdrawalDay: h.withdrawalDay,
        withdrawalDayEnd: h.withdrawalDayEnd,
      },
      create: h,
    });
    console.log(`   ✅ ${h.name} (${h.slug})`);
  }
}

async function seedDeals() {
  console.log('\n🤝 Seeding Deals...');

  const deals = [
    {
      id: 'aeeb29eb-649b-430b-8973-19678e687e48',
      bettingHouseSlug: 'esportivabet',
      name: 'EsportivaBet',
      cpa: 0,
      revshare: 0,
      baseline: 40,
      minAvgDepositPerFtd: 0,
      minQualifiedFtd: 15,
      exclusive: false,
      featured: true,
      newArrival: false,
      sortOrder: 10,
      paymentCpaLabel: '',
      paymentRevshareLabel: '',
      revenueType: '',
      revNegativeAccumulates: false,
      revNegativeOffsetsCpa: false,
      withdrawalIndicators: [] as string[],
      trafficSources: [] as string[],
      conditionsText: '',
      paymentNotes: '',
      logoUrl: 'https://raichu-uploads.s3.amazonaws.com/logo_esportiva-bet_SyUBvW.png',
      active: true,
      legacyKey: null as string | null,
    },
    {
      id: '9eee527d-cf92-4dc6-8561-105d78ea3590',
      bettingHouseSlug: 'mgm',
      name: 'BetMGM',
      cpa: 0,
      revshare: 0,
      baseline: 40,
      minAvgDepositPerFtd: 80,
      minQualifiedFtd: 15,
      exclusive: false,
      featured: true,
      newArrival: false,
      sortOrder: 10,
      paymentCpaLabel: '',
      paymentRevshareLabel: '',
      revenueType: '',
      revNegativeAccumulates: false,
      revNegativeOffsetsCpa: false,
      withdrawalIndicators: [] as string[],
      trafficSources: [] as string[],
      conditionsText: '',
      paymentNotes: '',
      logoUrl: 'https://cdn.brandfetch.io/idtGCz_avD/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1771319706513',
      active: true,
      legacyKey: null as string | null,
    },
    {
      id: '7cbda5dd-52bc-4631-9879-6de88e6c0ab9',
      bettingHouseSlug: 'superbet',
      name: 'Superbet',
      cpa: 0,
      revshare: 0,
      baseline: 0,
      minAvgDepositPerFtd: 80,
      minQualifiedFtd: 15,
      exclusive: false,
      featured: true,
      newArrival: true,
      sortOrder: 100,
      paymentCpaLabel: '',
      paymentRevshareLabel: '',
      revenueType: '',
      revNegativeAccumulates: false,
      revNegativeOffsetsCpa: false,
      withdrawalIndicators: [] as string[],
      trafficSources: [] as string[],
      conditionsText: '',
      paymentNotes: '',
      logoUrl: 'https://play-lh.googleusercontent.com/Q6uqNf1b4k7h4peN2r7jX1ok-Ur5l28cjm9qUb02Te2fyvo7iQRI09ReCZOQM26FSw=w240-h480-rw',
      active: true,
      legacyKey: null as string | null,
    },
  ];

  for (const d of deals) {
    await prisma.deal.upsert({
      where: { id: d.id },
      update: {
        name: d.name,
        cpa: d.cpa,
        revshare: d.revshare,
        baseline: d.baseline,
        minAvgDepositPerFtd: d.minAvgDepositPerFtd,
        minQualifiedFtd: d.minQualifiedFtd,
        exclusive: d.exclusive,
        featured: d.featured,
        newArrival: d.newArrival,
        sortOrder: d.sortOrder,
        paymentCpaLabel: d.paymentCpaLabel,
        paymentRevshareLabel: d.paymentRevshareLabel,
        revenueType: d.revenueType,
        revNegativeAccumulates: d.revNegativeAccumulates,
        revNegativeOffsetsCpa: d.revNegativeOffsetsCpa,
        withdrawalIndicators: d.withdrawalIndicators,
        trafficSources: d.trafficSources,
        conditionsText: d.conditionsText,
        paymentNotes: d.paymentNotes,
        logoUrl: d.logoUrl,
        active: d.active,
      },
      create: d,
    });
    console.log(`   ✅ ${d.name} (${d.bettingHouseSlug})`);
  }
}

async function seedSettings() {
  console.log('\n⚙️  Seeding Settings...');

  const settings = [
    { key: 'deposit_compliance_max_strikes', value: '3', label: 'test' },
    { key: 'deposit_compliance_running', value: 'false', label: 'Lock global: verificação de compliance em andamento' },
    { key: 'deposit_compliance_start_date', value: '2026-12-11', label: 'test' },
    { key: 'instagram_url', value: 'http://instagram.com/vexxa_company', label: 'Link do Instagram' },
    {
      key: 'login_announcement',
      value: '⚠️ AVISO IMPORTANTE — AUDITORIA DE MARÇO\n\nInformamos que todos os saques referentes ao mês de março estão temporariamente suspensos, pois estão passando por auditoria da Superbet.\n\nNovos saques serão liberados somente para CPAs contabilizados a partir de 01/04.\n\n📌 Regras atualizadas de saque:\n• Valor mínimo: R$100,00\n• Limite: 1 saque por dia\n• O saque será sempre do valor total disponível\n\nQualquer dúvida, entre em contato com o suporte.',
      label: 'Aviso exibido ao fazer login',
    },
    { key: 'login_announcement_active', value: 'false', label: 'Ativar aviso de login' },
    { key: 'maintenance_mode', value: 'false', label: 'Modo Manutenção' },
    { key: 'min_avg_deposit_per_cpa', value: '70', label: 'Depósito médio mínimo por CPA (R$)' },
    {
      key: 'min_avg_deposit_warning',
      value: 'Atenção: para solicitar saque, a média de depósito por CPA deve ser de no mínimo R$70,00. Operações com valor médio abaixo desse limite terão o link de afiliado bloqueado.',
      label: 'Aviso sobre depósito mínimo',
    },
    { key: 'min_daily_deposit_threshold', value: '70', label: 'test' },
    { key: 'min_withdrawal_amount', value: '100', label: 'Valor mínimo para saque (R$)' },
    { key: 'primary_color', value: '#3b82f6', label: 'Cor Primária' },
    { key: 'project_name', value: 'Vexxa company', label: 'Nome do Projeto' },
    { key: 'support_url', value: 'https://wa.me/558788580057', label: 'Link do Suporte' },
    { key: 'withdrawal_block_active', value: 'false', label: 'Bloquear saques (auditoria)' },
    {
      key: 'withdrawal_block_message',
      value: 'Os saques estão temporariamente bloqueados devido a uma auditoria em andamento referente ao mês de abril. Novos saques serão liberados apenas para CPAs contabilizados a partir de abril.',
      label: 'Mensagem de bloqueio de saque',
    },
  ];

  for (const s of settings) {
    await prisma.setting.upsert({
      where: { key: s.key },
      update: { label: s.label },   // preserve value if admin changed it; only update label
      create: s,
    });
  }
  console.log(`   ✅ ${settings.length} settings seeded (values preserved if already set)`);
}

async function seedProviderAccounts() {
  console.log('\n🔐 Seeding ProviderAccounts...');

  // LHT account (MGM)
  await prisma.providerAccount.upsert({
    where: { uq_account_name_provider: { name: 'LHT', provider: 'betboard' } },
    update: {
      apiBaseUrl: 'https://api-affiliates.mgaffiliates.site/api',
      email: 'lht@afiliadosexternos.com',
      encryptedPassword: requireEnv('LHT_PROVIDER_ENCRYPTED_PASSWORD'),
      active: true,
    },
    create: {
      id: '7a9b0582-68cf-44f3-a18d-6ec6a7e1fc13',
      name: 'LHT',
      provider: 'betboard',
      apiBaseUrl: 'https://api-affiliates.mgaffiliates.site/api',
      email: 'lht@afiliadosexternos.com',
      encryptedPassword: requireEnv('LHT_PROVIDER_ENCRYPTED_PASSWORD'),
      active: true,
    },
  });
  console.log('   ✅ ProviderAccount: LHT (betboard)');

  await prisma.providerAccountHouse.upsert({
    where: { uq_account_house: { providerAccountId: '7a9b0582-68cf-44f3-a18d-6ec6a7e1fc13', bettingHouseSlug: 'mgm' } },
    update: { bookmarkerId: '5c004b48-4213-4e1e-b028-01739154c10b', active: true },
    create: {
      id: 'a0a53c5b-ade9-49f2-9950-ae7c02f82178',
      providerAccountId: '7a9b0582-68cf-44f3-a18d-6ec6a7e1fc13',
      bettingHouseSlug: 'mgm',
      bookmarkerId: '5c004b48-4213-4e1e-b028-01739154c10b',
      extraConfig: {},
      active: true,
    },
  });
  console.log('   ✅ ProviderAccountHouse: LHT → mgm');

  // VEXXA account (EsportivaBET)
  await prisma.providerAccount.upsert({
    where: { uq_account_name_provider: { name: 'VEXXA', provider: 'betboard' } },
    update: {
      apiBaseUrl: 'https://api-affiliates.mgaffiliates.site/api',
      email: 'admin@vexxacompany.com',
      encryptedPassword: requireEnv('VEXXA_PROVIDER_ENCRYPTED_PASSWORD'),
      active: true,
    },
    create: {
      id: '74c6774d-d92a-4c3f-a21d-57d46908ae1d',
      name: 'VEXXA',
      provider: 'betboard',
      apiBaseUrl: 'https://api-affiliates.mgaffiliates.site/api',
      email: 'admin@vexxacompany.com',
      encryptedPassword: requireEnv('VEXXA_PROVIDER_ENCRYPTED_PASSWORD'),
      active: true,
    },
  });
  console.log('   ✅ ProviderAccount: VEXXA (betboard)');

  await prisma.providerAccountHouse.upsert({
    where: { uq_account_house: { providerAccountId: '74c6774d-d92a-4c3f-a21d-57d46908ae1d', bettingHouseSlug: 'esportivabet' } },
    update: { bookmarkerId: '02510c60-e702-479e-ada2-017e0b77f762', active: true },
    create: {
      id: '11ae756f-94f1-4c9a-b791-be60662d4016',
      providerAccountId: '74c6774d-d92a-4c3f-a21d-57d46908ae1d',
      bettingHouseSlug: 'esportivabet',
      bookmarkerId: '02510c60-e702-479e-ada2-017e0b77f762',
      extraConfig: {},
      active: true,
    },
  });
  console.log('   ✅ ProviderAccountHouse: VEXXA → esportivabet');
}

// ─── Step 0: Clear transactional tables ────────────────────────────────────
// NOTE: betting_houses, deals, settings, provider_accounts are seeded above.
// financial_ledger has no Mongo source — it is generated by the app at runtime.

async function clearTables() {
  console.log(
    '\n🗑️  Clearing transactional tables...',
  );

  await prisma.$executeRawUnsafe(`ALTER TABLE audit_logs DISABLE TRIGGER ALL`);

  const tablesToClear = [
    'prize_winners',
    'rank_prizes',
    'ranking_prizes',
    'push_subscriptions',
    'notification_snapshots',
    'notifications',
    'deposit_compliance_logs',
    'fraud_logs',
    'fraud_counts',
    'commission_logs',
    'audit_logs',
    'link_requests',
    'withdrawal_requests',
    'financial_ledger',
    'affiliate_data',
    'affiliate_links',
    'sync_logs',
    'refresh_tokens',
    'users',
  ];

  for (const table of tablesToClear) {
    await prisma.$executeRawUnsafe(`DELETE FROM "${table}"`);
    console.log(`   ✅ ${table} cleared`);
  }

  await prisma.$executeRawUnsafe(`ALTER TABLE audit_logs ENABLE TRIGGER ALL`);
  console.log('   ✅ All transactional tables cleared');
}

// ─── Step 1: Users (+ embedded affiliateLinks, fraudCounts) ──────

async function migrateUsers(mongo: MongoClient) {
  console.log('\n👤 Migrating Users...');
  const docs = await mongo.db().collection('users').find({}).toArray();

  let count = 0;
  for (const doc of docs) {
    const id = ensureId(doc._id);
    const pi = doc.paymentInfo ?? {};
    try {
      await prisma.user.create({
        data: {
          id,
          name: doc.name ?? '',
          email: (doc.email ?? '').toLowerCase().trim(),
          password: doc.password,
          role:
            doc.role?.toUpperCase() === 'ADMIN'
              ? UserRole.ADMIN
              : UserRole.AFFILIATE,
          status:
            (
              {
                pending: UserStatus.PENDING,
                approved: UserStatus.APPROVED,
                rejected: UserStatus.REJECTED,
                blocked: UserStatus.BLOCKED,
              } as any
            )[doc.status?.toLowerCase()] ?? UserStatus.PENDING,
          active: doc.active ?? true,
          ageVerified: doc.ageVerified ?? false,
          withdrawalBlocked: doc.withdrawalBlocked ?? false,
          bonusBalance: toDecimal(doc.bonusBalance),
          referralCode: doc.referralCode ?? null,
          cpf: doc.cpf ?? null,
          birthDate: doc.birthDate ? toDate(doc.birthDate) : null,
          whatsapp: doc.whatsapp ?? null,
          profileCompleted: doc.profileCompleted ?? false,
          pixKeyType: pi.pixKeyType ?? '',
          pixKey: pi.pixKey ?? '',
          bankName: pi.bankName ?? '',
          bankAgency: pi.bankAgency ?? '',
          bankAccount: pi.bankAccount ?? '',
          accountHolder: pi.accountHolder ?? '',
          depositComplianceAlertCount: doc.depositComplianceAlertCount ?? 0,
          depositCompliancePenalizedAt: doc.depositCompliancePenalizedAt
            ? toDate(doc.depositCompliancePenalizedAt)
            : null,
          createdAt: toDate(doc.createdAt),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
      });
      count++;
    } catch (e: any) {
      console.warn(
        `   ⚠️ Skipped user ${doc.email}: ${e.message?.slice(0, 100)}`,
      );
    }
  }
  console.log(`   ✅ ${count}/${docs.length} users created`);

  let refCount = 0;
  for (const doc of docs) {
    if (doc.referredBy) {
      const userId = ensureId(doc._id);
      const referrerId = mapId(doc.referredBy);
      if (referrerId) {
        try {
          await prisma.user.update({
            where: { id: userId },
            data: { referredById: referrerId },
          });
          refCount++;
        } catch {
          /* referrer may not exist */
        }
      }
    }
  }
  console.log(`   ✅ ${refCount} referral links set`);

  let linkCount = 0;
  for (const doc of docs) {
    if (!doc.affiliateLinks?.length) continue;
    const userId = ensureId(doc._id);
    for (const link of doc.affiliateLinks) {
      const house = normalizeHouse(link.bettingHouse ?? '');
      if (!house) continue;
      const houseExists = await prisma.bettingHouse.findUnique({
        where: { slug: house },
      });
      if (!houseExists) {
        console.warn(`   ⚠️ Skipped link for house "${house}" — not in PG`);
        continue;
      }
      const campaignId = (
        link.affiliateName ||
        link.affiliateId ||
        `legacy_${house}_${userId.slice(0, 8)}`
      ).trim();
      try {
        await prisma.affiliateLink.create({
          data: {
            userId,
            bettingHouse: house,
            affiliateId: link.affiliateId ?? '',
            campaignId,
            cpa: link.cpa != null ? toDecimal(link.cpa) : null,
            revshare: link.revshare != null ? toDecimal(link.revshare) : null,
          },
        });
        linkCount++;
      } catch (e: any) {
        console.warn(
          `   ⚠️ Skipped link ${campaignId}@${house}: ${e.message?.slice(0, 80)}`,
        );
      }
    }
  }
  console.log(`   ✅ ${linkCount} affiliate links migrated`);

  let fraudCount = 0;
  for (const doc of docs) {
    if (!doc.fraudCounts?.length) continue;
    const userId = ensureId(doc._id);
    for (const fc of doc.fraudCounts) {
      const house = normalizeHouse(fc.bettingHouse ?? '');
      if (!house) continue;
      try {
        await prisma.fraudCount.create({
          data: {
            userId,
            bettingHouse: house,
            count: fc.count ?? 0,
            updatedById: fc.updatedBy ? mapId(fc.updatedBy) : null,
          },
        });
        fraudCount++;
      } catch {
        /* duplicate or missing FK */
      }
    }
  }
  console.log(`   ✅ ${fraudCount} fraud counts migrated`);
}

// ─── Step 2: AffiliateData ──────────────────────────────────────

async function migrateAffiliateData(mongo: MongoClient) {
  console.log('\n📊 Migrating AffiliateData (this may take a while)...');
  const docs = await mongo.db().collection('affiliatedatas').find({}).toArray();
  let count = 0,
    skipped = 0;
  for (const doc of docs) {
    const campaignId = (doc.affiliateName || doc.campaignId || '').trim();
    const bettingHouse = (doc.bettingHouse ?? '').toLowerCase().trim();
    const campaignName = doc.campaignName ?? 'default';
    const utmCampaign = doc.utmCampaign ?? '';
    const date = toDate(doc.date);
    if (!campaignId || !bettingHouse) {
      skipped++;
      continue;
    }
    try {
      await prisma.affiliateData.upsert({
        where: {
          uq_affiliate_data: {
            campaignId,
            bettingHouse,
            date,
            campaignName,
            utmCampaign,
          },
        },
        update: {
          clicks: doc.clicks ?? 0,
          registrations: doc.registrations ?? 0,
          ftds: doc.ftds ?? 0,
          qftd: doc.qftd ?? 0,
          deposit: toDecimal(doc.deposit),
          revShare: toDecimal(doc.revShare ?? doc.revshare),
          cpaQualified: doc.cpaQualified ?? 0,
          cpaValue: toDecimal(doc.cpaValue),
          totalCommission: toDecimal(doc.totalCommission),
          lastSyncAt: doc.lastSyncAt ? toDate(doc.lastSyncAt) : new Date(),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
        create: {
          affiliateId: (doc.affiliateName || doc.affiliateId || '').trim(),
          campaignId,
          bettingHouse,
          campaignName,
          utmCampaign,
          date,
          clicks: doc.clicks ?? 0,
          registrations: doc.registrations ?? 0,
          ftds: doc.ftds ?? 0,
          qftd: doc.qftd ?? 0,
          deposit: toDecimal(doc.deposit),
          revShare: toDecimal(doc.revShare ?? doc.revshare),
          cpaQualified: doc.cpaQualified ?? 0,
          cpaValue: toDecimal(doc.cpaValue),
          totalCommission: toDecimal(doc.totalCommission),
          source: doc.source ?? 'otg-api',
          lastSyncAt: doc.lastSyncAt ? toDate(doc.lastSyncAt) : new Date(),
          createdAt: toDate(doc.createdAt),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
      });
      count++;
    } catch {
      skipped++;
    }
    if (count % 2000 === 0 && count > 0) process.stdout.write(`   ${count}...`);
  }
  console.log(`\n   ✅ ${count} affiliate data rows (${skipped} skipped)`);
}

// ─── Step 3: Withdrawals ────────────────────────────────────────

async function migrateWithdrawals(mongo: MongoClient) {
  console.log('\n💰 Migrating Withdrawals...');
  const docs = await mongo
    .db()
    .collection('withdrawalrequests')
    .find({})
    .toArray();
  let count = 0,
    skipped = 0;
  for (const doc of docs) {
    const userId = mapId(doc.user ?? doc.userId);
    if (!userId) {
      skipped++;
      continue;
    }
    let house = (doc.bettingHouse ?? 'superbet').toLowerCase().trim();
    if (house === 'all') house = 'superbet';
    const houseExists = await prisma.bettingHouse.findUnique({
      where: { slug: house },
    });
    if (!houseExists) {
      skipped++;
      continue;
    }
    try {
      await prisma.withdrawalRequest.create({
        data: {
          id: ensureId(doc._id),
          userId,
          amount: toDecimal(doc.amount),
          originalAmount: toDecimal(doc.originalAmount ?? doc.amount),
          withdrawalFee: toDecimal(doc.withdrawalFee),
          bettingHouse: house,
          pixKeyType: doc.pixKeyType ?? '',
          pixKey: doc.pixKey ?? '',
          bankName: doc.bankName ?? '',
          bankAgency: doc.bankAgency ?? '',
          bankAccount: doc.bankAccount ?? '',
          accountHolder: doc.accountHolder ?? '',
          status:
            (
              {
                pending: WithdrawalStatus.PENDING,
                approved: WithdrawalStatus.APPROVED,
                rejected: WithdrawalStatus.REJECTED,
              } as any
            )[doc.status?.toLowerCase()] ?? WithdrawalStatus.PENDING,
          requestNote: doc.requestNote ?? '',
          adminNote: doc.adminNote ?? '',
          approvedAt: doc.approvedAt ? toDate(doc.approvedAt) : null,
          approvedById: doc.approvedBy ? mapId(doc.approvedBy) : null,
          createdAt: toDate(doc.createdAt),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
      });
      count++;
    } catch {
      skipped++;
    }
  }
  console.log(`   ✅ ${count}/${docs.length} withdrawals (${skipped} skipped)`);
}

// ─── Step 4: Notifications ──────────────────────────────────────

async function migrateNotifications(mongo: MongoClient) {
  console.log('\n🔔 Migrating Notifications...');
  const docs = await mongo.db().collection('notifications').find({}).toArray();
  let count = 0,
    skipped = 0;
  const typeMap: Record<string, string> = {
    registration: 'REGISTRATION',
    commission_change: 'COMMISSION_CHANGE',
    withdrawal_approved: 'WITHDRAWAL_APPROVED',
    status_change: 'STATUS_CHANGE',
  };
  for (const doc of docs) {
    const userId = mapId(doc.userId);
    if (!userId) {
      skipped++;
      continue;
    }
    try {
      await prisma.notification.create({
        data: {
          userId,
          type: (typeMap[doc.type?.toLowerCase()] ?? 'GENERAL') as any,
          title: doc.title ?? '',
          message: doc.message ?? '',
          read: doc.read ?? false,
          metadata: doc.metadata ?? null,
          createdAt: toDate(doc.createdAt),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
      });
      count++;
    } catch {
      skipped++;
    }
    if (count % 5000 === 0 && count > 0) process.stdout.write(`   ${count}...`);
  }
  console.log(
    `\n   ✅ ${count}/${docs.length} notifications (${skipped} skipped)`,
  );
}

// ─── Step 5: CommissionLogs ─────────────────────────────────────

async function migrateCommissionLogs(mongo: MongoClient) {
  console.log('\n📝 Migrating CommissionLogs...');
  const docs = await mongo.db().collection('commissionlogs').find({}).toArray();
  let count = 0;
  for (const doc of docs) {
    const userId = mapId(doc.userId);
    try {
      await prisma.commissionLog.create({
        data: {
          userId,
          userName: doc.userName ?? '',
          userEmail: doc.userEmail ?? '',
          changedById: doc.changedById ? mapId(doc.changedById) : null,
          bettingHouse: (doc.bettingHouse ?? '').toLowerCase().trim(),
          field: doc.field ?? 'cpa',
          oldValue: doc.oldValue != null ? toDecimal(doc.oldValue) : null,
          newValue: doc.newValue != null ? toDecimal(doc.newValue) : null,
          createdAt: toDate(doc.createdAt),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
      });
      count++;
    } catch {
      /* FK missing */
    }
  }
  console.log(`   ✅ ${count}/${docs.length} commission logs`);
}

// ─── Step 6: LinkRequests ───────────────────────────────────────

async function migrateLinkRequests(mongo: MongoClient) {
  console.log('\n🔗 Migrating LinkRequests...');
  const docs = await mongo.db().collection('linkrequests').find({}).toArray();
  let count = 0,
    skipped = 0;
  for (const doc of docs) {
    const userId = mapId(doc.user ?? doc.userId);
    if (!userId) {
      skipped++;
      continue;
    }
    const slug = normalizeHouse(doc.bettingHouseSlug || doc.bettingHouse || '');
    if (!slug) {
      skipped++;
      continue;
    }
    try {
      await prisma.linkRequest.create({
        data: {
          id: ensureId(doc._id),
          userId,
          dealId: mapDealId(doc.deal ?? doc.dealId),
          bettingHouseSlug: slug,
          message: doc.message ?? '',
          status:
            (
              {
                pending: LinkRequestStatus.PENDING,
                fulfilled: LinkRequestStatus.FULFILLED,
                rejected: LinkRequestStatus.REJECTED,
              } as any
            )[doc.status?.toLowerCase()] ?? LinkRequestStatus.PENDING,
          links: doc.links ?? [],
          adminNote: doc.adminNote ?? '',
          fulfilledAt: doc.fulfilledAt ? toDate(doc.fulfilledAt) : null,
          fulfilledById: doc.fulfilledBy
            ? mapId(doc.fulfilledBy)
            : doc.fulfilledById
              ? mapId(doc.fulfilledById)
              : null,
          fulfilledByName: doc.fulfilledByName ?? '',
          createdAt: toDate(doc.createdAt),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
      });
      count++;
    } catch {
      skipped++;
    }
  }
  console.log(
    `   ✅ ${count}/${docs.length} link requests (${skipped} skipped)`,
  );
}

// ─── Step 7: AuditLogs ──────────────────────────────────────────

async function migrateAuditLogs(mongo: MongoClient) {
  console.log('\n📋 Migrating AuditLogs...');
  await prisma.$executeRawUnsafe(`ALTER TABLE audit_logs DISABLE TRIGGER ALL`);
  const docs = await mongo.db().collection('auditlogs').find({}).toArray();
  let count = 0,
    skipped = 0;
  for (const doc of docs) {
    const userId = mapId(doc.userId);
    if (!userId) {
      skipped++;
      continue;
    }
    try {
      await prisma.auditLog.create({
        data: {
          userId,
          userName: doc.userName ?? '',
          userEmail: doc.userEmail ?? '',
          action: doc.action ?? '',
          resource: doc.resource ?? '',
          method: doc.method ?? '',
          path: doc.path ?? '',
          ip: doc.ip ?? '',
          userAgent: doc.userAgent ?? '',
          statusCode: doc.statusCode ?? 200,
          details: doc.details ?? null,
          createdAt: toDate(doc.createdAt),
        },
      });
      count++;
    } catch {
      skipped++;
    }
  }
  await prisma.$executeRawUnsafe(`ALTER TABLE audit_logs ENABLE TRIGGER ALL`);
  console.log(`   ✅ ${count}/${docs.length} audit logs (${skipped} skipped)`);
}

// ─── Step 8: DepositComplianceLogs ──────────────────────────────

async function migrateDepositComplianceLogs(mongo: MongoClient) {
  console.log('\n📊 Migrating DepositComplianceLogs...');
  const docs = await mongo
    .db()
    .collection('depositcompliancelogs')
    .find({})
    .toArray();
  let count = 0,
    skipped = 0;
  const stMap: Record<string, string> = {
    pass: 'PASS',
    fail: 'FAIL',
    exempt: 'EXEMPT',
    penalty_applied: 'PENALTY_APPLIED',
  };
  const frMap: Record<string, string> = {
    my_data_below: 'MY_DATA_BELOW',
    team_below: 'TEAM_BELOW',
    both_below: 'BOTH_BELOW',
  };
  for (const doc of docs) {
    const userId = mapId(doc.userId);
    if (!userId) {
      skipped++;
      continue;
    }
    try {
      await prisma.depositComplianceLog.upsert({
        where: {
          userId_evaluationDate: {
            userId,
            evaluationDate: toDate(doc.evaluationDate),
          },
        },
        update: {},
        create: {
          userId,
          evaluationDate: toDate(doc.evaluationDate),
          myDataDeposit: toDecimal(doc.myDataDeposit),
          myDataQftd: doc.myDataQftd ?? 0,
          myDataAvg: toDecimal(doc.myDataAvg),
          teamDeposit: toDecimal(doc.teamDeposit),
          teamQftd: doc.teamQftd ?? 0,
          teamAvg: toDecimal(doc.teamAvg),
          teamSkipped: doc.teamSkipped ?? false,
          threshold: toDecimal(doc.threshold),
          status: (stMap[(doc.status ?? '').toLowerCase()] ?? 'PASS') as any,
          failReason: (frMap[(doc.failReason ?? '').toLowerCase()] ??
            null) as any,
          alertCountAfter: doc.alertCountAfter ?? 0,
          withdrawalBlockedForDay: doc.withdrawalBlockedForDay ?? false,
          penaltyApplied: doc.penaltyApplied ?? false,
          processedAt: doc.processedAt ? toDate(doc.processedAt) : new Date(),
          createdAt: toDate(doc.createdAt),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
      });
      count++;
    } catch {
      skipped++;
    }
  }
  console.log(
    `   ✅ ${count}/${docs.length} deposit compliance logs (${skipped} skipped)`,
  );
}

// ─── Step 9: FraudLogs ──────────────────────────────────────────

async function migrateFraudLogs(mongo: MongoClient) {
  console.log('\n🔍 Migrating FraudLogs...');
  const docs = await mongo.db().collection('fraudlogs').find({}).toArray();
  let count = 0,
    skipped = 0;
  for (const doc of docs) {
    const userId = mapId(doc.userId);
    const changedById = mapId(doc.changedBy);
    if (!userId || !changedById) {
      skipped++;
      continue;
    }
    try {
      await prisma.fraudLog.create({
        data: {
          userId,
          changedById,
          bettingHouse: (doc.bettingHouse ?? '').toLowerCase().trim(),
          oldCount: doc.oldCount ?? 0,
          newCount: doc.newCount ?? 0,
          reason: doc.reason ?? '',
          createdAt: toDate(doc.createdAt),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
      });
      count++;
    } catch {
      skipped++;
    }
  }
  console.log(`   ✅ ${count}/${docs.length} fraud logs (${skipped} skipped)`);
}

// ─── Step 10: SyncLogs ──────────────────────────────────────────

async function migrateSyncLogs(mongo: MongoClient) {
  console.log('\n🔄 Migrating SyncLogs...');
  const docs = await mongo.db().collection('synclogs').find({}).toArray();
  let count = 0,
    skipped = 0;
  const stMap: Record<string, string> = {
    running: 'RUNNING',
    success: 'SUCCESS',
    error: 'ERROR',
  };
  for (const doc of docs) {
    const house = (doc.bettingHouse ?? '').toLowerCase().trim();
    const houseExists = await prisma.bettingHouse.findUnique({
      where: { slug: house },
    });
    if (!houseExists) {
      skipped++;
      continue;
    }
    try {
      await prisma.syncLog.create({
        data: {
          bettingHouse: house,
          startTime: doc.startTime
            ? toDate(doc.startTime)
            : toDate(doc.createdAt),
          endTime: doc.endTime ? toDate(doc.endTime) : null,
          status: (stMap[(doc.status ?? '').toLowerCase()] ?? 'SUCCESS') as any,
          triggeredBy: doc.triggeredBy ?? 'cron',
          periodStart: doc.periodo?.inicio ? toDate(doc.periodo.inicio) : null,
          periodEnd: doc.periodo?.fim ? toDate(doc.periodo.fim) : null,
          totalRecords: doc.stats?.totalRecords ?? 0,
          inserted: doc.stats?.inserted ?? 0,
          updated: doc.stats?.updated ?? 0,
          errors: doc.stats?.errors ?? 0,
          errorMessage: doc.errorMessage ?? null,
          createdAt: toDate(doc.createdAt),
        },
      });
      count++;
    } catch {
      skipped++;
    }
  }
  console.log(`   ✅ ${count}/${docs.length} sync logs (${skipped} skipped)`);
}

// ─── Step 11: NotificationSnapshots ─────────────────────────────

async function migrateNotificationSnapshots(mongo: MongoClient) {
  console.log('\n📸 Migrating NotificationSnapshots...');
  const docs = await mongo
    .db()
    .collection('notificationsnapshots')
    .find({})
    .toArray();
  let count = 0,
    skipped = 0;
  for (const doc of docs) {
    const userId = mapId(doc.userId);
    if (!userId) {
      skipped++;
      continue;
    }
    const bh = (doc.bettingHouse ?? '').toLowerCase().trim();
    try {
      await prisma.notificationSnapshot.upsert({
        where: { userId_bettingHouse: { userId, bettingHouse: bh } },
        update: {
          clicks: doc.clicks ?? 0,
          registrations: doc.registrations ?? 0,
          ftds: doc.ftds ?? 0,
          cpaQualified: doc.cpaQualified ?? 0,
          lastCheckedAt: doc.lastCheckedAt
            ? toDate(doc.lastCheckedAt)
            : new Date(),
        },
        create: {
          userId,
          bettingHouse: bh,
          clicks: doc.clicks ?? 0,
          registrations: doc.registrations ?? 0,
          ftds: doc.ftds ?? 0,
          cpaQualified: doc.cpaQualified ?? 0,
          lastCheckedAt: doc.lastCheckedAt
            ? toDate(doc.lastCheckedAt)
            : new Date(),
          createdAt: toDate(doc.createdAt),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
      });
      count++;
    } catch {
      skipped++;
    }
  }
  console.log(
    `   ✅ ${count}/${docs.length} notification snapshots (${skipped} skipped)`,
  );
}

// ─── Step 12: PushSubscriptions ─────────────────────────────────

async function migratePushSubscriptions(mongo: MongoClient) {
  console.log('\n📲 Migrating PushSubscriptions...');
  const docs = await mongo
    .db()
    .collection('pushsubscriptions')
    .find({})
    .toArray();
  let count = 0,
    skipped = 0;
  for (const doc of docs) {
    const userId = mapId(doc.user ?? doc.userId);
    if (!userId) {
      skipped++;
      continue;
    }
    const p256dh = doc.keys?.p256dh ?? doc.p256dh ?? '';
    const auth = doc.keys?.auth ?? doc.auth ?? '';
    if (!doc.endpoint || !p256dh || !auth) {
      skipped++;
      continue;
    }
    try {
      await prisma.pushSubscription.upsert({
        where: { userId_endpoint: { userId, endpoint: doc.endpoint } },
        update: { p256dh, auth },
        create: {
          userId,
          endpoint: doc.endpoint,
          p256dh,
          auth,
          createdAt: toDate(doc.createdAt),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
      });
      count++;
    } catch {
      skipped++;
    }
  }
  console.log(
    `   ✅ ${count}/${docs.length} push subscriptions (${skipped} skipped)`,
  );
}

// ─── Step 13: RankingPrizes → 3 tables ──────────────────────────

async function migrateRankingPrizes(mongo: MongoClient) {
  console.log('\n🏆 Migrating RankingPrizes...');
  const docs = await mongo.db().collection('rankingprizes').find({}).toArray();
  let prizeCount = 0,
    rankCount = 0,
    winnerCount = 0;
  const ptMap: Record<string, string> = {
    balance: 'BALANCE',
    physical: 'PHYSICAL',
    other: 'OTHER',
  };
  const stMap: Record<string, string> = {
    active: 'ACTIVE',
    ended: 'ENDED',
    finalized: 'FINALIZED',
  };
  for (const doc of docs) {
    const id = ensureId(doc._id);
    const createdById = doc.createdBy ? mapId(doc.createdBy) : null;
    if (!createdById) continue;
    const userExists = await prisma.user.findUnique({
      where: { id: createdById },
    });
    if (!userExists) continue;
    try {
      await prisma.rankingPrize.create({
        data: {
          id,
          title: doc.title ?? '',
          description: doc.description ?? '',
          prizeType: (ptMap[(doc.prizeType ?? '').toLowerCase()] ??
            'OTHER') as any,
          prizeValue: toDecimal(doc.prizeValue),
          prizeLabel: doc.prizeLabel ?? '',
          icon: doc.icon ?? '🏆',
          startDate: toDate(doc.startDate),
          endDate: toDate(doc.endDate),
          winnersCount: doc.winnersCount ?? 1,
          targetCpa: doc.targetCpa ?? 0,
          status: (stMap[(doc.status ?? '').toLowerCase()] ?? 'ACTIVE') as any,
          createdById,
          finalizedById: doc.finalizedBy ? mapId(doc.finalizedBy) : null,
          finalizedAt: doc.finalizedAt ? toDate(doc.finalizedAt) : null,
          createdAt: toDate(doc.createdAt),
          updatedAt: toDate(doc.updatedAt ?? doc.createdAt),
        },
      });
      prizeCount++;
    } catch (e: any) {
      console.warn(`   ⚠️ Prize "${doc.title}": ${e.message?.slice(0, 80)}`);
      continue;
    }

    for (const rp of doc.prizes ?? []) {
      try {
        await prisma.rankPrize.create({
          data: {
            rankingPrizeId: id,
            rank: rp.rank,
            prizeType: (ptMap[(rp.prizeType ?? '').toLowerCase()] ??
              'OTHER') as any,
            prizeValue: toDecimal(rp.prizeValue),
            prizeLabel: rp.prizeLabel ?? '',
            icon: rp.icon ?? '',
          },
        });
        rankCount++;
      } catch {
        /* dupe */
      }
    }

    for (const w of doc.winners ?? []) {
      const winnerId = mapId(w.userId);
      if (!winnerId) continue;
      try {
        await prisma.prizeWinner.create({
          data: {
            rankingPrizeId: id,
            userId: winnerId,
            userName: w.userName ?? '',
            campaignId: w.affiliateName ?? '',
            cpaAchieved: w.cpaAchieved ?? 0,
            rank: w.rank ?? 0,
            prizeType: (ptMap[(w.prizeType ?? '').toLowerCase()] ??
              'OTHER') as any,
            prizeValue: toDecimal(w.prizeValue),
            prizeLabel: w.prizeLabel ?? '',
            redeemed: w.redeemed ?? false,
            redeemedAt: w.redeemedAt ? toDate(w.redeemedAt) : null,
            balanceCredited: w.balanceCredited ?? false,
          },
        });
        winnerCount++;
      } catch {
        /* dupe or FK */
      }
    }
  }
  console.log(
    `   ✅ ${prizeCount} prizes | ${rankCount} rank prizes | ${winnerCount} winners`,
  );
}

// ─── Main ───────────────────────────────────────────────────────

async function main() {
  console.log('═'.repeat(60));
  console.log('  FRESH MongoDB → PostgreSQL Migration');
  console.log('  Preserving: betting_houses, deals, settings, providers');
  console.log('═'.repeat(60));

  const mongo = new MongoClient(MONGO_URI);
  await mongo.connect();
  console.log('✅ Connected to MongoDB (mjmcompany)');

  const collections = await mongo.db().listCollections().toArray();
  console.log(
    `Collections: ${collections
      .map((c) => c.name)
      .sort()
      .join(', ')}`,
  );

  try {
    // 1. Seed static tables first (upsert — idempotent)
    await seedBettingHouses();
    await seedDeals();
    await seedSettings();
    await seedProviderAccounts();

    // 2. Build deal ID map (Mongo → PG)
    await buildDealMap(mongo);

    // 3. Clear & re-migrate transactional tables
    await clearTables();

    await migrateUsers(mongo);
    await migrateAffiliateData(mongo);
    await migrateWithdrawals(mongo);
    await migrateNotifications(mongo);
    await migrateCommissionLogs(mongo);
    await migrateLinkRequests(mongo);
    await migrateAuditLogs(mongo);
    await migrateDepositComplianceLogs(mongo);
    await migrateFraudLogs(mongo);
    await migrateSyncLogs(mongo);
    await migrateNotificationSnapshots(mongo);
    await migratePushSubscriptions(mongo);
    await migrateRankingPrizes(mongo);

    console.log('\n' + '═'.repeat(60));
    console.log('  Migration complete!');
    console.log(`  ID mappings: ${idMap.size}`);
    console.log('═'.repeat(60));
  } finally {
    await mongo.close();
    await prisma.$disconnect();
  }
}

main().catch((err) => {
  console.error('Migration failed:', err);
  process.exit(1);
});
